language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar install
 - cd tests

script:
 - phpunit --coverage-clover ./build/clover.xml

after_script:
  - php vendor/bin/coveralls
